CREATE TABLE verificacion (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    inspection_id BIGINT NOT NULL UNIQUE,
    vehicle_unit_id BIGINT NOT NULL,
    verification_order_id BIGINT NOT NULL,
    verification_center_id BIGINT NULL,
    folio_verificacion VARCHAR(60) NOT NULL UNIQUE,
    materia VARCHAR(40) NOT NULL DEFAULT 'GASOLINA',
    precio DOUBLE NULL,
    multa DOUBLE NULL,
    fecha_verificacion TIMESTAMP(6) NOT NULL,
    veredicto VARCHAR(20) NOT NULL,
    overall_comment TEXT NULL,
    archived BIT NOT NULL DEFAULT b'0',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_verificacion_inspection FOREIGN KEY (inspection_id) REFERENCES inspections(id),
    CONSTRAINT fk_verificacion_vehicle_unit FOREIGN KEY (vehicle_unit_id) REFERENCES vehicle_units(id),
    CONSTRAINT fk_verificacion_order FOREIGN KEY (verification_order_id) REFERENCES verification_orders(id),
    CONSTRAINT fk_verificacion_center FOREIGN KEY (verification_center_id) REFERENCES verification_centers(id)
);

CREATE TABLE evaluacion (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    verificacion_id BIGINT NOT NULL UNIQUE,
    luces_galibo VARCHAR(40) NULL,
    luces_altas VARCHAR(40) NULL,
    luces_bajas VARCHAR(40) NULL,
    luces_demarcadoras_delanteras VARCHAR(40) NULL,
    luces_demarcadoras_traseras VARCHAR(40) NULL,
    luces_indicadoras VARCHAR(40) NULL,
    faro_izquierdo VARCHAR(40) NULL,
    faro_derecho VARCHAR(40) NULL,
    luces_direccionales_delanteras VARCHAR(40) NULL,
    luces_direccionales_traseras VARCHAR(40) NULL,
    llantas_rines_delanteros VARCHAR(40) NULL,
    llantas_rines_traseros VARCHAR(40) NULL,
    llantas_masas_delanteras VARCHAR(40) NULL,
    llantas_masas_traseras VARCHAR(40) NULL,
    llantas_presion_delantera_izquierda DOUBLE NULL,
    llantas_presion_delantera_derecha DOUBLE NULL,
    llantas_presion_trasera_izquierda_1 DOUBLE NULL,
    llantas_presion_trasera_izquierda_2 DOUBLE NULL,
    llantas_presion_trasera_derecha_1 DOUBLE NULL,
    llantas_presion_trasera_derecha_2 DOUBLE NULL,
    llantas_profundidad_delantera_izquierda DOUBLE NULL,
    llantas_profundidad_delantera_derecha DOUBLE NULL,
    llantas_profundidad_trasera_izquierda_1 DOUBLE NULL,
    llantas_profundidad_trasera_izquierda_2 DOUBLE NULL,
    llantas_profundidad_trasera_derecha_1 DOUBLE NULL,
    llantas_profundidad_trasera_derecha_2 DOUBLE NULL,
    llantas_tuercas_delantera_izquierda VARCHAR(40) NULL,
    llantas_tuercas_delantera_izquierda_faltantes INT NULL,
    llantas_tuercas_delantera_izquierda_rotas INT NULL,
    llantas_tuercas_delantera_derecha VARCHAR(40) NULL,
    llantas_tuercas_delantera_derecha_faltantes INT NULL,
    llantas_tuercas_delantera_derecha_rotas INT NULL,
    llantas_tuercas_trasera_izquierda VARCHAR(40) NULL,
    llantas_tuercas_trasera_izquierda_faltantes INT NULL,
    llantas_tuercas_trasera_izquierda_rotas INT NULL,
    llantas_tuercas_trasera_derecha VARCHAR(40) NULL,
    llantas_tuercas_trasera_derecha_faltantes INT NULL,
    llantas_tuercas_trasera_derecha_rotas INT NULL,
    direccion_brazo_pitman VARCHAR(40) NULL,
    direccion_manijas_puertas VARCHAR(40) NULL,
    direccion_chavetas VARCHAR(40) NULL,
    direccion_chavetas_faltantes INT NULL,
    aire_frenos_compresor VARCHAR(40) NULL,
    aire_frenos_tanques_aire VARCHAR(40) NULL,
    aire_frenos_tiempo_carga_psi DOUBLE NULL,
    aire_frenos_tiempo_carga_tiempo DOUBLE NULL,
    motor_emisiones_humo VARCHAR(40) NULL,
    motor_emisiones_gobernado VARCHAR(40) NULL,
    otros_caja_direccion VARCHAR(40) NULL,
    otros_deposito_aceite VARCHAR(40) NULL,
    otros_parabrisas VARCHAR(40) NULL,
    otros_limpiaparabrisas VARCHAR(40) NULL,
    otros_juego VARCHAR(40) NULL,
    otros_escape VARCHAR(40) NULL,
    comentario_luces TEXT NULL,
    comentario_llantas TEXT NULL,
    comentario_direccion TEXT NULL,
    comentario_aire_frenos TEXT NULL,
    comentario_motor_emisiones TEXT NULL,
    comentario_otros TEXT NULL,
    comentarios_generales TEXT NULL,
    evidence_count INT NOT NULL DEFAULT 0,
    archived BIT NOT NULL DEFAULT b'0',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_evaluacion_verificacion FOREIGN KEY (verificacion_id) REFERENCES verificacion(id)
);
